@startuml
hide footbox
skinparam ArrowFontStyle normal

participant ":ScheduleCommand" as ScheduleCommand
participant "students:StudentList" as StudentList
participant "targetStudent:Student" as Student
participant "newLesson:Lesson" as Lesson
participant "existingLesson:Lesson" as ExistingLesson
participant "ui:Ui" as Ui

[-> ScheduleCommand : execute(students, ui)
activate ScheduleCommand

loop activeSize times
    ScheduleCommand -> StudentList : getActiveStudent(i)
    activate StudentList
    StudentList --> ScheduleCommand : student
    deactivate StudentList

    ScheduleCommand -> Student : getName()
    activate Student
    Student --> ScheduleCommand : name
    deactivate Student
end

create Lesson
ScheduleCommand -> Lesson : Lesson(day, startTime, endTime)
activate Lesson
Lesson --> ScheduleCommand : newLesson
deactivate Lesson

ScheduleCommand -> Student : addLesson(newLesson)
activate Student

loop all existing lessons
    Student -> ExistingLesson : isOverlapping(newLesson)
    activate ExistingLesson
    ExistingLesson --> Student : isOverlap
    deactivate ExistingLesson
end

alt isOverlap == true
    Student --> ScheduleCommand : TutorSwiftException
    deactivate Student

    [<-- ScheduleCommand : TutorSwiftException

else isOverlap == false
    deactivate Student

    ScheduleCommand -> Student : getName()
    activate Student
    Student --> ScheduleCommand : "Alice"
    deactivate Student

    ScheduleCommand -> Ui : showLessonScheduled("Alice", newLesson)
    activate Ui
    deactivate Ui
end

[<-- ScheduleCommand
deactivate ScheduleCommand
destroy ScheduleCommand
@enduml